### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by mj6uc** [robojamison/pycropper#2]
Hi, 

I just cloned it to run on 3 sample images (1.jpg, 2 and 3). It processed the first, on the second...

...
...
Processing 2.jpg...
Image type: JPEG; mode: RGB; dimensions: 1280x720
Sampling background color...
Searching for top edge...
Traceback (most recent call last):
  File "cropper.py", line 175, in <module>
    main()
  File "cropper.py", line 172, in main
    process(file_path)
  File "cropper.py", line 66, in process
    if not is_like_bg_color(pixel_map[i, y]):
  File "cropper.py", line 26, in is_like_bg_color
    bg_r, bg_g, bg_b = bg_color[0], bg_color[1], bg_color[2]
IndexError: tuple index out of range

**Comment by mj6uc** [comment]
Here is a "public domain" image that replicates the issue:
"https://3.bp.blogspot.com/-A9nxz1PE4ks/WujaSDC5ixI/AAAAAAAAFJM/ul6dtveR5K8z5mG05Gv2eVU4KvUM4UEwQCLcBGAs/s1600/unnamed%2B%25284%2529.png"

mv unnamed.png img/1.png


Processing 1.png...
Image type: PNG; mode: RGB; dimensions: 1600x900
Sampling background color...
Searching for top edge...
Traceback (most recent call last):
  File "cropper.py", line 175, in <module>
    main()
  File "cropper.py", line 172, in main
    process(file_path)
  File "cropper.py", line 66, in process
    if not is_like_bg_color(pixel_map[i, y]):
  File "cropper.py", line 26, in is_like_bg_color
    bg_r, bg_g, bg_b = bg_color[0], bg_color[1], bg_color[2]
IndexError: tuple index out of range

**Comment by spades1404** [comment]
This happens when the pixel values for the 4 corners are not the same and therefore the bgcolor tuple is empty. A quick bodge fix is to remove the statement where it checks the corner colours and just execute the code thats normally in that if statements anyways. Although a better fix would be to build in tolerances for slightly gradient background colours - which is well beyond my capabilities.

**Comment by jamisonbryant** [comment]
Thank you for the report, and thank you for the public domain image. I will look into this as soon as I have a chance. I just moved into a new house and my home office is kind of all over the place right now.
